name: Create and Upload Release ZIP

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ZIP archive
        run: |
          zip -r plugin.audio.digitallyimported.zip . -x '*.git*'

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: plugin.audio.digitallyimported.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
